# Use a imagem base do Nginx
FROM nginx:alpine

# Remova a configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copie o arquivo de configuração do Nginx para o contêiner
COPY nginx.conf /etc/nginx/nginx.conf

# Copie um arquivo HTML de exemplo para o diretório de conteúdo do Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponha a porta 80
EXPOSE 80
